### ISSUE TITLE
Chapter06

### ISSUE THREAD

**Issue by poonxup** [rddill-IBM/ZeroToBlockchain#18]
In Chapter 6, when I execute "node index", and got this error message.

admin$ node index
module.js:540
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/admin/Downloads/ZeroToBlockchain-master/Chapter06/index.js:17:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by poonxup** [comment]
It's already fixed. I have found out that ,you must install the following 

npm install express
npm install mime
npm install body-parser
npm install cfenv
npm install cookie-parser
npm install express-session
npm install vcap_services
npm install uuid
npm install connect-busboy
npm install ejs
npm install date-format
npm install extend
npm install composer-common
npm install composer-admin
npm install composer-client
npm install sleep
npm install websocket
npm install fabric-client
