### ISSUE TITLE
The license header file does'nt exist 

### ISSUE THREAD

**Issue by sivachaitanya** [rddill-IBM/ZeroToBlockchain#23]
Hi,

So I have executed till ./buildAndDeploy.sh which ran perfectly and launched the docker container and rest-server. However when I try to do npm test as described in Chapter 04 it is failing with following error, can you please help me fix this ?

ubuntu@ip-172-31-18-205:~/ZeroToBlockchain/Chapter04/network$ npm test

> zerotoblockchain-network@0.1.5 pretest /home/ubuntu/ZeroToBlockchain/Chapter04/network
> npm run lint

> zerotoblockchain-network@0.1.5 lint /home/ubuntu/ZeroToBlockchain/Chapter04/network
> eslint ./network

> zerotoblockchain-network@0.1.5 postlint /home/ubuntu/ZeroToBlockchain/Chapter04/network
> npm run licchk

> zerotoblockchain-network@0.1.5 licchk /home/ubuntu/ZeroToBlockchain/Chapter04/network
> license-check

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: The license header file doesn`t exist header.txt
    at readLicenseHeaderFile (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/gulp-license-check/index.js:113:53)
    at isLicenseHeaderPresent (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/gulp-license-check/index.js:172:23)
    at checkHeaderFromBuffer (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/gulp-license-check/index.js:81:7)
    at DestroyableTransform._transform (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/gulp-license-check/index.js:41:5)
    at DestroyableTransform.Transform._read (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/home/ubuntu/ZeroToBlockchain/Chapter04/network/node_modules/readable-stream/lib/_stream_readable.js:619:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zerotoblockchain-network@0.1.5 licchk: `license-check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zerotoblockchain-network@0.1.5 licchk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-03-28T14_08_10_751Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zerotoblockchain-network@0.1.5 postlint: `npm run licchk`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zerotoblockchain-network@0.1.5 postlint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-03-28T14_08_10_778Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by sivachaitanya** [comment]
Working fine now, deleted all the softwares I installed on my AWS instance and gone through the steps sepcified and it worked like a charm, Thanks for great tutorial !
