### ISSUE TITLE
ZerotoBlockchain Chapter06

### ISSUE THREAD

**Issue by HuyHoang2017** [rddill-IBM/ZeroToBlockchain#29]
Dear Mr @rddill-IBM , I deployed ZerotoBlockchain with Chapter06 successfully. But when I create a member with Name and Email, I get this error. It stops service and stop port 6001, then I have to run "node index" command to continue. 

user@user-virtual-machine:~/Chapter06$ node index
Listening locally on port 6001
[1] at: 14:30:11.202 Url is: /api/getSupportedLanguages
[2] at: 14:30:11.244 Url is: /composer/admin/getMembers
[3] at: 14:30:11.326 Url is: /composer/admin/getMembers
[4] at: 14:30:11.333 Url is: /composer/admin/getMembers
[5] at: 14:30:11.338 Url is: /composer/admin/getMembers
[6] at: 14:30:12.125 Url is: /api/selectedPrompts
[7] at: 14:30:13.124 Url is: /api/getTextLocations
[8] at: 14:31:28.748 Url is: /api/getSupportedLanguages
[9] at: 14:31:28.752 Url is: /composer/admin/getMembers
[10] at: 14:31:28.757 Url is: /composer/admin/getMembers
[11] at: 14:31:28.765 Url is: /composer/admin/getMembers
[12] at: 14:31:28.770 Url is: /composer/admin/getMembers
[13] at: 14:31:28.780 Url is: /api/getTextLocations
[14] at: 14:31:28.793 Url is: /api/selectedPrompts
[15] at: 14:31:31.083 Url is: /composer/admin/getRegistries
[16] at: 14:32:01.992 Url is: /composer/admin/addMember
c@gmail.com not in Buyer registry.
/home/user/Chapter06/controller/restapi/features/composer/queryBlockChain.js:122
                        bcEvents.registerBlockEvent(function(event) {svc.cs_connection.sendUTF(JSON.stringify(e                                                         vent));});
                                                                                       ^

TypeError: Cannot read property 'sendUTF' of null
    at /home/user/Chapter06/controller/restapi/features/composer/queryBlockChain.js:122:88
    at /home/user/Chapter06/node_modules/fabric-client/lib/EventHub.js:761:4
    at Array.forEach (<anonymous>)
    at EventHub._processBlockOnEvents (/home/user/Chapter06/node_modules/fabric-client/lib/EventHub.js:759:36)
    at ClientDuplexStream.<anonymous> (/home/user/Chapter06/node_modules/fabric-client/lib/EventHub.js:312:10)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)

![image](https://user-images.githubusercontent.com/34642653/39857577-02c49f16-545e-11e8-89b9-81a189928a41.png)

**Comment by rddill-IBM** [comment]
Please update to the current release of the tutorial. This error is generally caused by failing to copy over all of the code from the answers folder into each of the appropriate files in your folders.
