### ISSUE TITLE
Error npm install on Chapter03

### ISSUE THREAD

**Issue by veeru-rayidi** [rddill-IBM/ZeroToBlockchain#3]
N_TYPE grpc::node::Call::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node/ext/call.cc:616:20: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
       info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
                    ^
../src/node/ext/call.cc:625:19: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         argc, argv);
                   ^
In file included from /home/veeru/.node-gyp/8.9.0/include/node/v8.h:26:0,
                 from /home/veeru/.node-gyp/8.9.0/include/node/node.h:63,
                 from ../src/node/ext/call.cc:38:
/home/veeru/.node-gyp/8.9.0/include/node/v8.h:3832:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const)
                               ^
/home/veeru/.node-gyp/8.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
grpc_node.target.mk:133: recipe for target 'Release/obj.target/grpc_node/src/node/ext/call.o' failed
make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
make: Leaving directory '/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/veeru/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-28-generic
gyp ERR! command "/home/veeru/.nvm/versions/node/v8.9.0/bin/node" "/home/veeru/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/veeru/.nvm/versions/node/v8.9.0/bin/node /home/veeru/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.10.0-28-generic
node-pre-gyp ERR! command "/home/veeru/.nvm/versions/node/v8.9.0/bin/node" "/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute '/home/veeru/.nvm/versions/node/v8.9.0/bin/node /home/veeru/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/veeru/Documents/GitHub/ZeroToBlockchain/Chapter03/node_modules/hfc/node_modules/grpc/src/node/extension_binary' (1)
npm WARN The package http is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rddill-IBM** [comment]
long error log. What operating system are you using? Did you follow the instructions on using either the Ubuntu part 1 & part 2 scripts or the OSX set up script?

**Comment by veeru-rayidi** [comment]
UBUNTU 14.04 LTS (VB IMage)..Yes i have fallowed all the instructions..Is there any specific version of docker that i need to install?. i did tried coule of times..but same issue is coming

**Comment by rddill-IBM** [comment]
Did you install a 32-bit image or a 64-bit image of Ubuntu? Follow the instructions here if you're not positive that you have a 32-bit image installed: [https://askubuntu.com/questions/12493/how-can-i-find-the-version-of-ubuntu-that-is-installed](https://askubuntu.com/questions/12493/how-can-i-find-the-version-of-ubuntu-that-is-installed)
